//Inspired by: https://github.com/jenkinsci/kubernetes-plugin/blob/master/README.md#container-group-support
podTemplate(yaml: """
  apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
  spec:
    securityContext:
      runAsUser: 10000
      runAsGroup: 10000
      fsGroup: 10000
    containers:
    - name: maven
      image: maven:3-eclipse-temurin
      tty: true
      command: ['cat']
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
    - name: golang
      image: golang:latest
      tty: true
      command: ['cat']
""") {

    node(POD_LABEL) {
        stage('Get a Maven project') {
            git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            container('maven') {
                stage('Build a Maven project') {
                    sh """
                        mvn -B clean install
                    """
                }
            }
        }

        stage('Get a Golang project') {
            git url: 'https://github.com/golang/example.git'
            container('golang') {
                stage('Build a Go project') {
                    sh """
                    # Prepare it
                    mkdir -p /go/src/github.com/golang
                    ln -s `pwd` /go/src/github.com/golang/example
                    cd /go/src/github.com/golang/example/hello
                    export GOCACHE=/go/.cache
                    # Build it
                    go build hello.go

                    # Run it
                    ./hello
                    """
                }
            }
        }

    }
}
