node {
    agent any
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name:'MSG_PREFIX', defaultValue:'Line ', description:'Message prefix')
        string(name:'COUNT_TO', defaultValue:'1000', description:'Count up to this number')
    }
    stage("Count") {
        sh '''
            set +x
            for i in $(seq 1 "$COUNT_TO")
            do
              echo "$MSG_PREFIX" $i
            done
        '''
    }
}
