#!/usr/bin/env groovy

properties([
    parameters([
        string(name:'SECRETID', description:'ID of the secret'),
        string(name:'EXPECTEDUSER', description:'Name of the user'),
        string(name:'EXPECTEDPWD', description:'Password of the user')
    ])
])

stage('test'){
  node {

    echo "SECRETID: "+SECRETID      
    echo "EXPECTEDUSER: "+EXPECTEDUSER      
    echo "EXPECTEDPWD: "+EXPECTEDPWD      
      
    echo "Test 1 - withCredentials"
    withCredentials([usernamePassword(credentialsId: SECRETID, usernameVariable: 'USER', passwordVariable: 'PASSWORD')]){
        if (!USER.equals(EXPECTEDUSER)) error("Username don't match")
        if (!PASSWORD.equals(EXPECTEDPWD)) error("Password don't match")
        sh """
            # Test1 password masking
            echo "User: ${USER}"
            echo "Password: ${PASSWORD}"
        """
        sh '''
            # Test2 password masking
            echo "User: ${USER}"
            echo "Password: ${PASSWORD}"
        '''
    }
     
    echo "Test 2 - withCredentials in withEnv"
    withEnv(['testenv=test']) {
        withCredentials([usernamePassword(credentialsId: SECRETID, usernameVariable: 'USER', passwordVariable: 'PASSWORD')]){
            if (!USER.equals(EXPECTEDUSER)) error("Username don't match")
            if (!PASSWORD.equals(EXPECTEDPWD)) error("Pwd don't match")
            sh """
                # Test password masking
                echo "User: ${USER}"
                echo "Password: ${PASSWORD}"
            """
            sh '''
                # Test2 password masking
                echo "User: ${USER}"
                echo "Password: ${PASSWORD}"
            '''
        }
    }

    echo "Test 3 - withEnv in withCredentials"
    withCredentials([usernamePassword(credentialsId: SECRETID, usernameVariable: 'USER', passwordVariable: 'PASSWORD')]){
        withEnv(['testenv=test']) {
            if (!USER.equals(EXPECTEDUSER)) error("Username don't match")
            if (!PASSWORD.equals(EXPECTEDPWD)) error("Pwd don't match")
            sh """
                # Test password masking
                echo "User: ${USER}"
                echo "Password: ${PASSWORD}"
            """
            sh '''
                # Test2 password masking
                echo "User: ${USER}"
                echo "Password: ${PASSWORD}"
            '''
        }
    }

  }
}
