#!/usr/bin/env groovy

properties([
    parameters([
        string(name:'SECRETID', description:'ID of the secret'),
        string(name:'EXPECTEDUSER', description:'Name of the user'),
        string(name:'EXPECTEDPWD', description:'Password of the user')
    ])
])

stage('test'){
  node {
    withCredentials([usernamePassword(credentialsId: SECRETID, usernameVariable: 'USER', passwordVariable: 'PWD')]){
        if (!USER.equals(EXPECTEDUSER)) error("Username don't match")
        if (!PWD.equals(EXPECTEDPWD)) error("Pwd don't match")
        sh """
            # Test password masking 1
            echo "User: ${USER}"
            echo "Password: ${PWD}"
        """
        sh '''
            # Test password masking 2
            echo "User: ${USER}"
            echo "Password: ${PWD}"
        '''
    }
  }
}
